# This workflow automates the CI/CD pipeline for the application.

name: CI/CD - Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your repo
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Setup gcloud CLI with service account authentication
    - name: Authenticate to Google Cloud
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}  # JSON key stored as GitHub Secret
        export_default_credentials: true

    # Step 3: Build and Push Docker Image to Artifact Registry
    - name: Build and Push Docker image
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        REGION: us-central1             # Change if needed
        REPO: my-gcr-repo               # Your Artifact Registry repo
        IMAGE: my-app-image             # Name of your image
      run: |
        gcloud auth configure-docker $REGION-docker.pkg.dev -q
        docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:latest .
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:latest

    # Step 4: Deploy to Cloud Run
    - name: Deploy to Cloud Run
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        REGION: us-central1
        SERVICE_NAME: my-cloudrun-service
        REPO: my-gcr-repo
        IMAGE: my-app-image
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:latest \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated
